// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Zephyr.Db;

#nullable disable

namespace Zephyr.Migrations
{
    [DbContext(typeof(ZephyrDbContext))]
    [Migration("20250305194906_Metar")]
    partial class Metar
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.2");

            modelBuilder.Entity("Zephyr.Entities.Metar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("MetarText")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ObservationDateTimeZulu")
                        .HasColumnType("TEXT");

                    b.Property<string>("Station")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("TemperatureCelsius")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Metars");
                });
#pragma warning restore 612, 618
        }
    }
}
